AWSTemplateFormatVersion: 2010-09-09

Resources:
  MigrateService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Join ['', [!Ref StackName, KratosMigrateService]]
      Cluster: !Ref Cluster
      TaskDefinition: !Ref MigrateTask
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 100
      DesiredCount: 1
      # HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          # change to DISABLED if you're using private subnets that have access to a NAT gateway
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref ServiceSubnet

  MigrateTask:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - LogGroup
      - KratosDB
    Properties:
      Family: !Join ['', [!Ref StackName, MigrateTaskDefinition]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref ServiceTaskRole
      ContainerDefinitions:
        - Name: KratosDBMigrate
          Image: !Join [':', [!Ref KratosMigrateRepository, !Ref KratosMigrateVersion]]
          # Send logs to CloudWatch Logs
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
