apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/fvosbe-bachelor-thesis/hello-go
  labels:
    cloud.googleapis.com/location: europe-west1
  name: hello-go
  namespace: '91740078209'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1000'
        client.knative.dev/user-image: gcr.io/fvosbe-bachelor-thesis/hello-go
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 298.0.0
      name: hello-go-00004-hak
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/fvosbe-bachelor-thesis/hello-go
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
